name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v6
      
#      - name: Go setup
#        uses: actions/setup-go@v6
#        with:
#          cache: false
#          go-version-file: go.mod
#
#      - name: Install build dependencies
#        run: make deps
#
#      - name: Code build
#        run: make build
#
#      - name: Code format
#        run: make format && git diff --exit-code
#
#      - name: Code test
#        run: make test
#
#      - name: Code lint
#        run: make lint

      - name: Create a file
        run: |
          echo "some yadda" > zaraza.txt
          echo "status=success" >> $GITHUB_OUTPUT 

      - name: Tagger
        uses: agukrapo/tagger@c1a331f2e431cd75b49f2a74323873f0be23a435
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          assets: zaraza.txt
